services: 
  app:    
    container_name: app
    networks:
      - skynetbe3
    build: .
    volumes:
      - $PWD/app/:/opt/app
    links:
      - db    
  db:
    container_name: db
    image: mysql
    networks:
      - skynetbe3
    command: --default-authentication-plugin=mysql_native_password    
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    volumes:
      - $PWD/db/:/var/lib/mysql/
  busy:
    container_name: busybox
    image: busybox
    networks:
      - skynetbe3
networks:
  skynetbe3:

