- hosts: all
  tasks:
    
    - name: 'Instalando repositório do zabbix'
      apt:
        deb: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu20.04_all.deb
    - name: 'Instalando repositório do zabbix'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600       
    - name: 'Instala zabbix no Sistema operacional'
      apt:
        name: '{{ item }}'
        state: latest
      become: yes
      with_items:
        - zabbix-server-mysql
        - zabbix-frontend-php
        - zabbix-apache-conf
        - zabbix-sql-scripts
        - zabbix-agent
        - mysql-server
        - python3-mysql.connector
        - python3-mysqldb
        - python3-pymysql

    - name: 'Cria o banco do MySQL'
      mysql_db: 
        name: zabbix
        login_user: root
        state: present
      become: yes

    - name: 'Cria o usuário do MySQL'
      mysql_user:
        name: zabbix
        password: 12345
        priv: 'zabbix.*:ALL'
        state: present
      become: yes