- hosts: all
  tasks:
    
    - name: 'Instalando repositório do zabbix'
      get_url:
        url: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu20.04_all.deb
        dest: /tmp/
        mode: '0440'
    - name: 'Instalando o repositório'
      dpkg_selections:
        name: zabbix
        selection: install
    
    - name: 'Update dos repositórios'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: 'Instala pacotes do sistema operacional'
      apt:
        name: '{{ item }}'
        state: latest
      become: yes
      with_items:
        - php
        - apache2
        - libapache2-mod-php
        - git
     - name: 'Criando banco'
     - name: 'Criando usuario para o banco'